FROM --platform=linux/amd64 alpine:3.12
ARG ADDON_NAME=nuclei_templates
LABEL maintainer="peeyush.tyagi@getastra.com"
WORKDIR /nuclei
COPY ${ADDON_NAME} ./${ADDON_NAME}

CMD ["sh", "-c", "cp -r /nuclei/* /temp_mount"]